apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-basket
  labels:
    app: stress-basket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-basket
  template:
    metadata:
      name: stress-basket
      labels:
        app: stress-basket
      annotations: {
        "sidecar.istio.io/inject": "false"
      }
    spec:
      containers:
        - name: stress-basket
          image: alpine:3.12
          command:
          - /bin/sh
          - -c
          - "while true; do wget -q -O- http://basket/api/v1/Basket/test; done"