apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-catalog
  labels:
    app: stress-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-catalog
  template:
    metadata:
      name: stress-catalog
      labels:
        app: stress-catalog
      annotations: {
        "sidecar.istio.io/inject": "false"
      }
    spec:
      containers:
        - name: stress-catalog
          image: alpine:3.12
          command:
          - /bin/sh
          - -c
          - "while true; do wget -q -O- http://catalog/api/v1/Catalog; done"