apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-discount
  labels:
    app: stress-discount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-discount
  template:
    metadata:
      name: stress-discount
      labels:
        app: stress-discount
      annotations: {
        "sidecar.istio.io/inject": "false"
      }
    spec:
      containers:
        - name: stress-discount
          image: alpine:3.12
          command:
          - /bin/sh
          - -c
          - "while true; do wget -q -O- http://discount/api/v1/Discount/product1; done"